title: NFCogos docs
description: The global cannabis ecosystem
remote_theme: just-the-docs/just-the-docs

url: docs.nfcogos.com

aux_links:
  Docs Repository: https://github.com/notsag-dev/docs-nfcogos
